from django.db import models

# Create your models here.


class Estado (models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=1000)
    full_name = models.CharField(max_length=1000)
    population = models.IntegerField()
    area_km2 = models.FloatField()
    population_density = models.FloatField()
    demonym = models.CharField(max_length=50)
    latitude = models.FloatField()
    longitude = models.FloatField()
    ibge_code = models.IntegerField()
    main_zip_code = models.CharField(max_length=1000)
    zip_code_range = models.CharField(max_length=1000)
    seo_title = models.CharField(max_length=1000)
    meta_description = models.TextField()
    appropriate_preposition = models.CharField(max_length=2000)
    description_text = models.TextField()
    map_embed = models.URLField()
    gdp = models.CharField(max_length=1000)
    hdi = models.FloatField()
    climate = models.CharField(max_length=52000)
    history = models.TextField()
    main_activities = models.JSONField(default=list)
    tourist_attractions = models.JSONField(default=list)
    uf =  models.CharField(max_length=52000)


class Cidade (models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=1000)
    full_name = models.CharField(max_length=1000)
    state = models.ForeignKey(Estado, on_delete=models.CASCADE)
    population = models.IntegerField()
    area_km2 = models.FloatField()
    population_density = models.FloatField()
    demonym = models.CharField(max_length=5000)
    latitude = models.FloatField()
    longitude = models.FloatField()
    ibge_code = models.IntegerField()
    main_zip_code = models.CharField(max_length=10000)
    zip_code_range = models.CharField(max_length=2000)
    seo_title = models.CharField(max_length=160)
    meta_description = models.TextField()
    appropriate_preposition = models.CharField(max_length=2002)
    description_text = models.TextField()
    map_embed = models.URLField()
    gdp = models.CharField(max_length=1000)
    hdi = models.FloatField()
    climate = models.CharField(max_length=50050)
    history = models.TextField()
    main_activities = models.JSONField()  
    tourist_attractions = models.JSONField()


class Bairro(models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=1000)
    full_name = models.CharField(max_length=1000)
    city = models.ForeignKey(Cidade,on_delete=models.CASCADE)
    population = models.IntegerField()
    area_km2 = models.FloatField()
    population_density = models.FloatField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    zip_code = models.CharField(max_length=10000)
    seo_title = models.CharField(max_length=10000)
    meta_description = models.TextField()
    appropriate_preposition = models.CharField(max_length=2000)
    description_text = models.TextField()
    map_embed = models.URLField()
    gdp = models.CharField(max_length=1000)
    hdi = models.FloatField()
    climate = models.CharField(max_length=20000)
    history = models.TextField()
    main_activities = models.JSONField() 
    points_of_interest = models.JSONField()