from django.db import models




class Estado (models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=255)
    population = models.IntegerField()
    area_km2 = models.FloatField()
    population_density = models.FloatField()
    demonym = models.CharField(max_length=50)
    latitude = models.FloatField()
    longitude = models.FloatField()
    ibge_code = models.IntegerField()
    main_zip_code = models.CharField(max_length=10)
    zip_code_range = models.CharField(max_length=20)
    seo_title = models.CharField(max_length=160)
    meta_description = models.TextField()
    appropriate_preposition = models.CharField(max_length=2)
    description_text = models.TextField()
    map_embed = models.URLField()
    gdp = models.BigIntegerField()
    hdi = models.FloatField()
    climate = models.CharField(max_length=50)
    history = models.TextField()


class Cidade (models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=255)
    state = models.ForeignKey(Estado, on_delete=models.CASCADE)
    population = models.IntegerField()
    area_km2 = models.FloatField()
    population_density = models.FloatField()
    demonym = models.CharField(max_length=50)
    latitude = models.FloatField()
    longitude = models.FloatField()
    ibge_code = models.IntegerField()
    main_zip_code = models.CharField(max_length=10)
    zip_code_range = models.CharField(max_length=20)
    seo_title = models.CharField(max_length=160)
    meta_description = models.TextField()
    appropriate_preposition = models.CharField(max_length=2)
    description_text = models.TextField()
    map_embed = models.URLField()
    gdp = models.BigIntegerField()
    hdi = models.FloatField()
    climate = models.CharField(max_length=50)
    history = models.TextField()
    main_activities = models.JSONField()  
    tourist_attractions = models.JSONField()


class Bairro(models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=255)
    city = models.ForeignKey(Cidade,on_delete=models.CASCADE)
    population = models.IntegerField()
    area_km2 = models.FloatField()
    population_density = models.FloatField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    zip_code = models.CharField(max_length=10)
    seo_title = models.CharField(max_length=160)
    meta_description = models.TextField()
    appropriate_preposition = models.CharField(max_length=2)
    description_text = models.TextField()
    map_embed = models.URLField()
    gdp = models.BigIntegerField()
    hdi = models.FloatField()
    climate = models.CharField(max_length=50)
    history = models.TextField()
    main_activities = models.JSONField() 
    points_of_interest = models.JSONField()