# Generated by Django 5.1.7 on 2025-04-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='climate',
            field=models.CharField(max_length=5200),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='seo_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='zip_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='appropriate_preposition',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='climate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='main_zip_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='seo_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='zip_code_range',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estado',
            name='appropriate_preposition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estado',
            name='climate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estado',
            name='demonym',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estado',
            name='main_zip_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estado',
            name='seo_title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='estado',
            name='zip_code_range',
            field=models.CharField(max_length=220),
        ),
    ]
