# Generated by Django 5.1.7 on 2025-04-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0003_alter_bairro_appropriate_preposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='main_activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='estado',
            name='tourist_attractions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='estado',
            name='uf',
            field=models.CharField(default=[], max_length=52000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='gdp',
            field=models.CharField(max_length=1000),
        ),
    ]
