# Generated by Django 5.1.7 on 2025-04-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0005_alter_estado_gdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='gdp',
            field=models.CharField(max_length=1000),
        ),
    ]
